language: python

python:
  - "3.6"  # 3.7

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE test_db;"
  - mysql -u root -e "CREATE USER test_user WITH PASSWORD 'test_user';"
  - mysql -u root -e "ALTER USER test_user CREATEDB;"

env:
  - SECRET_KEY=this-should-be-secret DATABASE_NAME=test_db DATABASE_USER=test_user DATABASE_PASSWORD=test_user DATABASE_HOST=localhost DATABASE_PORT=5432

script:
  - python manage.py test
