language: python

python:
  - "3.6"  # 3.7

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE test_db;"
  - mysql -u root -e "CREATE USER 'test_user'@'%' IDENTIFIED BY 'test_user';"
  - mysql -u root -e "GRANT ALL ON test_db.* TO 'test_user'@'%';"

env:
  - SECRET_KEY=this-should-be-secret DATABASE_NAME=test_db DATABASE_USER=test_user DATABASE_PASSWORD=test_user DATABASE_HOST=localhost DATABASE_PORT=3306

script:
  - python manage.py test
