language: python

python:
  - "3.6"  # 3.7

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - mysql

before_script:
  - mysql -c "CREATE DATABASE test_db;" -U root
  - mysql -c "CREATE USER test_user WITH PASSWORD 'test_user';" -U root
  - mysql -c "ALTER USER test_user CREATEDB;" -U root

env:
  - SECRET_KEY=this-should-be-secret DATABASE_NAME=test_db DATABASE_USER=test_user DATABASE_PASSWORD=test_user DATABASE_HOST=localhost DATABASE_PORT=5432

script:
  - python manage.py test
